# Generated by Django 5.1.6 on 2025-02-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profesor', models.CharField(max_length=100)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.cursos')),
                ('Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.materias')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calificacion', models.IntegerField()),
                ('Periodo', models.IntegerField()),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.estudiantes')),
                ('Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.materias')),
                ('Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.profesores')),
            ],
        ),
    ]
