# Generated by Django 5.1.6 on 2025-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='Periodo',
            field=models.IntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')]),
        ),
    ]
