# Generated by Django 5.1.6 on 2025-02-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanelControl', '0002_alter_calificaciones_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='Profesor',
        ),
    ]
