# Generated by Django 5.1.6 on 2025-02-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelControl', '0004_materias_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='Curso',
        ),
        migrations.AddField(
            model_name='profesores',
            name='Cursos',
            field=models.ManyToManyField(to='PanelControl.cursos'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Curso',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='materias',
            name='Materia',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together={('Estudiante', 'Materia', 'Periodo')},
        ),
    ]
