# Generated by Django 5.1.6 on 2025-02-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelControl', '0005_remove_profesores_curso_profesores_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='Profesor',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
