# Generated by Django 5.1.6 on 2025-02-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelControl', '0007_alter_profesores_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesores',
            name='Profesor',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
