# Generated by Django 5.1.6 on 2025-02-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelControl', '0009_alter_profesores_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notas', models.TextField()),
                ('FechaDeRegistro', models.DateField(auto_now=True)),
                ('Estudiante_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.estudiantes')),
                ('Maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.profesores')),
            ],
        ),
    ]
