# Generated by Django 5.1.6 on 2025-02-27 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelControl', '0010_apuntes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Old', models.IntegerField()),
                ('New', models.IntegerField()),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.estudiantes')),
                ('Maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanelControl.profesores')),
            ],
        ),
    ]
