# Generated by Django 5.1.6 on 2025-02-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelControl', '0011_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='Cambio',
            field=models.CharField(default='Agregar', max_length=30),
        ),
    ]
